"""empty message

Revision ID: 26643ec393b1
Revises: f3ce91ae4819
Create Date: 2023-08-30 07:44:26.128959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26643ec393b1'
down_revision = 'f3ce91ae4819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
